### PR TITLE
Feat 61 upgrade derived dds

### LINKED ISSUE #61: `DataDescriptionUpgrader` does not handle generating `DerivedDataDescriptions`
Currently the `DataDescriptionUpgrader` always upgrades towards a `DataDescription` object, and needs to upgrade to `DerivedDataDescription` in the case that the asset is derived. 

Are there other circumstances where a different DD model should be used?

### PR DESCRIPTION
**Pull request by Sun-flow**
closes #61 

`DataDescriptionUpgrader` has not been handling `DerivedDataDescriptions`. Changed some values to allow for detection at ingest of which model type should be output, and output the corresponding model type (`DerivedDataDescription` or `DataDescription`).

Added some test examples for Derived DDs. Also renamed the dd examples folder to not be exaspim specific, since multiple other modalities exist in the examples now.

### CODE REVIEW

**Review by dbirman — COMMENTED** [review]
Seems to be working for me, the new derived test throws a lot of serialization warnings but I assume that's unavoidable? 

```
UserWarning: Pydantic serializer warnings:
  Expected `Union[BEHAVIOR, CONFOCAL, ECEPHYS, EXASPIM, FIP, HCR, HSFP, ISI, MERFISH, MRI, MESOSPIM, MOTOR_OBSERVATORY, MULTIPLANE_OPHYS, SLAP2, SINGLE_PLANE_OPHYS, SMARTSPIM]` but got `dict` - serialized value may not be as expected
  Expected `datetime` but got `str` - serialized value may not be as expected
  Expected `Union[AIBS, AIND, COLUMBIA, HUST, JANELIA, NYU, OTHER]` but got `dict` - serialized value may not be as expected
  Expected `Funding` but got `dict` - serialized value may not be as expected
  Expected `PIDName` but got `str` - serialized value may not be as expected
  Expected `Union[BEHAVIOR, BEHAVIOR_VIDEOS, CONFOCAL, EMG, ECEPHYS, FIB, FMOST, ICEPHYS, ISI, MRI, MERFISH, POPHYS, SLAP, SPIM]` but got `dict` - serialized value may not be as expected
  Expected `Union[BEHAVIOR, BEHAVIOR_VIDEOS, CONFOCAL, EMG, ECEPHYS, FIB, FMOST, ICEPHYS, ISI, MRI, MERFISH, POPHYS, SLAP, SPIM]` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
.
```

**Comment by Sun-flow** [comment]
> Seems to be working for me, the new derived test throws a lot of serialization warnings but I assume that's unavoidable?
> 
> ```
> UserWarning: Pydantic serializer warnings:
>   Expected `Union[BEHAVIOR, CONFOCAL, ECEPHYS, EXASPIM, FIP, HCR, HSFP, ISI, MERFISH, MRI, MESOSPIM, MOTOR_OBSERVATORY, MULTIPLANE_OPHYS, SLAP2, SINGLE_PLANE_OPHYS, SMARTSPIM]` but got `dict` - serialized value may not be as expected
>   Expected `datetime` but got `str` - serialized value may not be as expected
>   Expected `Union[AIBS, AIND, COLUMBIA, HUST, JANELIA, NYU, OTHER]` but got `dict` - serialized value may not be as expected
>   Expected `Funding` but got `dict` - serialized value may not be as expected
>   Expected `PIDName` but got `str` - serialized value may not be as expected
>   Expected `Union[BEHAVIOR, BEHAVIOR_VIDEOS, CONFOCAL, EMG, ECEPHYS, FIB, FMOST, ICEPHYS, ISI, MRI, MERFISH, POPHYS, SLAP, SPIM]` but got `dict` - serialized value may not be as expected
>   Expected `Union[BEHAVIOR, BEHAVIOR_VIDEOS, CONFOCAL, EMG, ECEPHYS, FIB, FMOST, ICEPHYS, ISI, MRI, MERFISH, POPHYS, SLAP, SPIM]` but got `dict` - serialized value may not be as expected
>   return self.__pydantic_serializer__.to_python(
> .
> ```

We have this issue in a number of areas, and I've gotten used to ignoring it. Unsure where it comes from, @jtyoung84 might be able to offer more insight.

**Comment by Sun-flow** [comment]
My assumption would be that it is just something that happens when a model gets an unexpected type (that is convertable into an expected type), and is just letting us know that it has done that.

**Comment by Sun-flow** [comment]
Could consider using a check on the asset name to determine derived status, rather than using `data_description.data_level`, as we've had some assets come through with incorrect data descriptions already marking derived assets as raw (in this case, they lacked the correct derivation info anyways, so they wouldn't upgrade without re-deriving them, and it's probably best to leave them alone and fix them in a different way.)

**Comment by dbirman** [comment]
> Could consider using a check on the asset name to determine derived status, rather than using `data_description.data_level`, as we've had some assets come through with incorrect data descriptions already marking derived assets as raw (in this case, they lacked the correct derivation info anyways, so they wouldn't upgrade without re-deriving them, and it's probably best to leave them alone and fix them in a different way.)

This is what I do in the qc app (because the data_descriptions are all invalid), I just check if there's 4 parts or 7 when you split by the underscore character. Maybe use that as a backup if the level field is missing?

**Review by jtyoung84 — APPROVED** [review]

**Pull request merged**
